name: Dacapo Tests

on:
  pull_request:
    branhes:
      - master

jobs:
  test:
    runs-on: ubuntu-18.04
    steps:
      # Checkout repos and submodules
      - uses: actions/checkout@v2
        with:
          # CI_ACCESS_TOKEN is a secret set with the repo
          token: ${{ secrets.CI_ACCESS_TOKEN }}
          submodules: true
      - name: Update git submodules
        run: git submodule update --remote --recursive
      - name: Set credential for cargo dependency
        run: sed -i 's/ssh:\/\/git@github.com\/mmtk/https:\/\/qinsoon:${{ secrets.CI_ACCESS_TOKEN }}@github.com\/mmtk/g' mmtk/Cargo.toml
      - name: Setup Environments
        run: RUSTUP_TOOLCHAIN=nightly-2019-08-26 ./.github/scripts/ci-setup.sh

      # Run the tests
      - name: Dacapo Tests
        run: RUSTUP_TOOLCHAIN=nightly-2019-08-26 ./.github/scripts/ci-test.sh